# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  online-web:
    image: docker.io/nginx:1.23-alpine
    container_name: online-web
    restart: unless-stopped
    volumes:
      - ./wwwroot:/var/www/forum
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    # uncomment to expose port directly
    # normally behind centeral traefik defined in production-manifests/services/traefik
    # ports:
    #   - "80:80"

    # join danger-internal and traefik-backend networks
    # comment out the traefik lines here and in the networks: stanza below
    # if you uncomment the port exposure above
    networks:
      online-internal: {}
      traefik-backend: {}
  
  online-php:
    # production: track "prod" tag on ghcr.io
    # image: ghcr.io/wetfish/online:prod
    # for development, build the image
    # TODO: once ghcr.io autobuilds in place, change this
    build: .
    container_name: online-php
    restart: unless-stopped
    env_file:
      - ./php.env
    volumes:
      - ./wwwroot:/var/www/forum
      - ./utils:/var/www/utils
      - ./config/php.ini:/usr/local/etc/php/conf.d/settings.ini:ro
      - ./config/php.conf:/usr/local/etc/php-fpm.d/zz-php.conf:ro
    networks:
      online-internal: {}

  online-db:
    image: docker.io/mariadb:10.10
    container_name: online-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    # built-in healthcheck script
    healthcheck:
      test: ["healthcheck.sh", "--su=mysql", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - ./config/docker.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
    networks:
      online-internal: {}


networks:
  # ephemeral, created for us by compose
  online-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true

