# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  online-web:
    image: ghcr.io/wetfish/online:prod-nginx
    container_name: online-web
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    # join online-internal and traefik-backend networks
    # comment out the traefik lines here and in the networks: stanza below
    # if you uncomment the port exposure above
    networks:
      online-internal: {}
      traefik-backend: {}
  
  online-php:
    # production: track "prod" tag on ghcr.io
    image: ghcr.io/wetfish/online:prod-php
    container_name: online-php
    restart: unless-stopped
    env_file:
      - ./php.env
    volumes:
      - ./config/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf:ro
      - ./config/php-fpm-pool.conf:/etc/php/5.6/fpm/pool.d/www.conf:ro
      - ./config/php.ini:/etc/php/5.6/fpm/php.ini:ro
    networks:
      online-internal: {}

  online-db:
    image: docker.io/mariadb:10.10
    container_name: online-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    volumes:
      - ./config/docker.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db/data:/var/lib/mysql
    networks:
      online-internal: {}

networks:
  # ephemeral, created for us by compose
  online-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true

